# --- Authentication and Identity ---
# This is the most critical fix. It tells the pods to use the Service
# Account that has been granted IAM permissions.
serviceAccount:
  create: true  # The chart uses 'create', not 'enable'
  name: "open-webui-pia" 

# --- Resource and Scheduling Management ---
# These are the fixes for the pod scheduling issues.
ollama:
  enabled: false
pipelines:
  enabled: false
affinity: {}

# --- Storage Configuration ---
# This explicitly tells the chart to use your default StorageClass.
persistence:
  storageClassName: "auto-ebs-sc"
  
# --- Database Configuration ---
# This ensures the app connects to your external RDS instance.
extraEnvVars:
  - name: "DATABASE_URL"
    valueFrom:
      secretKeyRef:
        name: "openwebui-db-credentials"
        key: "url"
  - name: "VECTOR_DB"
    value: "pgvector"