apiVersion: v1
kind: Service
metadata:
  name: litellm-service
  namespace: litellm
spec:
  selector:
    app: litellm
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  type: ClusterIP
